#ifdef SPANISH
   		#define STR0001 "Separacion"
   		#define STR0002 "Seleccione:"
   		#define STR0003 "Orden de Separacion"
   		#define STR0004 "Pedido de Venta"
   		#define STR0005 "Factura"
   		#define STR0006 "Orden Producion"
   		#define STR0007 "Expedicion"
   		#define STR0008 "Expedicion Seleccione"
   		#define STR0009 "Operador no registrado"
		#define STR0010 "Aviso"
   		#define STR0011 "El contenido informado en el parametro MV_IACD01 debe existir en la tabla CB5."
   		#define STR0012 "Proceso de separacion finalizado"
   		#define STR0013 "¿Desea revertir la separacion ?"
   		#define STR0014 "Atencion"
   		#define STR0015 "Informaciones"
   		#define STR0016 "Revierte"
   		#define STR0017 "Ultima Ventana"
		#define STR0018 "Volumen"
		#define STR0019 "¿Confirma la salida?"
		#define STR0020 "Salta"
		#define STR0021 "Div.Etiqueta"
		#define STR0022 "Div.Pallet"
		#define STR0023 "Todavia hay items sin separar. ¿Desea separalos ahora?"
		#define STR0024 "Vaya al almacen"
		#define STR0025 "Enter para continuar"
		#define STR0026 "Vaya al almacen "
		#define STR0027 "Vaya al almacen "
		#define STR0028 "Vaya a la direccion"
		#define STR0029 "Falla al grabar el movimiento TM "
		#define STR0030 "Lea la direccion"
		#define STR0031 "Inconsistencia de Base, producto "
		#define STR0032 " no encontrado"
		#define STR0033 "item "
		#define STR0034 "items "
		#define STR0035 "volumen "
		#define STR0036 "volumenes "
		#define STR0037 "Separe "
		#define STR0038 "Lote: "
		#define STR0039 "Producto"
		#define STR0040 "Descripcion"
		#define STR0041 "Ctd"
		#define STR0042 "Lote"
		#define STR0043 "Sublote"
		#define STR0044 "Num. Serie"
		#define STR0045 "Separe"
   		#define STR0046 "Lea la etiqueta"
   		#define STR0047 "Ctd "
   		#define STR0048 "Lea el producto"
   		#define STR0049 "Lea la caja"
		#define STR0050 "Lea la etiq. avulsa"
		#define STR0051 "¡Item separado no localizado!"
		#define STR0052 "Cantidad"
   		#define STR0053 "Almacen"
   		#define STR0054 "Direccion"
   		#define STR0055 "Subvolumen"
   		#define STR0056 "Num.Serie"
   		#define STR0057 "Id Etiqueta"
   		#define STR0058 "Embalaje"
   		#define STR0059 "Lea el volumen:"
   		#define STR0060 "Tecle ENTER para"
   		#define STR0061 "nuevo volumen.    "
		#define STR0062 "Lea el volumen o ENTER p/ nuevo volume"
		#define STR0063 "Lea el volumen"
   		#define STR0064 "Digite el codigo del"
   		#define STR0065 "tipo de embalaje"
   		#define STR0066 "Imprimiendo etiqueta de volumen "
   		#define STR0067 "Etiqueta invalida"
   		#define STR0068 "Codigo de volumen no registrado"
   		#define STR0069 "Volumen pertenece al pedido "
   		#define STR0070 "Volume pertenece a la factura "
   		#define STR0071 "Embalaje sin registrar"
   		#define STR0072 "Orden de separacion no encontrada."
   		#define STR0073 "Orden de Preseparacion "
		#define STR0074 "Codigo Invalido"
		#define STR0075 "Orden de separacion en proceso de embalaje"
		#define STR0076 "Orden de separacion con embalaje finalizada"
		#define STR0077 "Orden de separacion tiene Nota generada"
		#define STR0078 "Orden de separacion tiene etiquetas oficias de volumenes"
		#define STR0079 "Orden de separacion en proceso de embarque"
		#define STR0080 "Orden de separacion ya Embarcada"
		#define STR0081 "Orden Separacion iniciada por el operador "
		#define STR0082 ". ¿Desea continuar ?"
		#define STR0083 "Orden Separacion ya esta en desarrollo...!"
		#define STR0084 "Direccion invalida"
		#define STR0085 "Direccion Bloqueada."
		#define STR0086 "Etiqueta invalida, producto pertenece a un Pallet"
		#define STR0087 "Direccion asociada a esta etiqueta esta diferente"
		#define STR0088 "Etiqueta ya leida"
		#define STR0089 "Producto diferente"
		#define STR0090 "Cantidad mayor que lo necesario"
		#define STR0091 "Lote invalido"
		#define STR0092 "Lote no existe"
		#define STR0093 "Saldo insuficiente en stock"
		#define STR0094 "Pallet excede la cantidad por separar"
		#define STR0095 "Etiqueta de producto diferente"
		#define STR0096 "Cantidad invalida"
		#define STR0097 "Cantidad mayor que solicitado"
		#define STR0098 "Informe el codigo"
		#define STR0099 "da divergencia:"
		#define STR0100 "Informe el codigo de la divergencia:"
		#define STR0101 "Divergencia:"
		#define STR0102 "Ocurrencia no registrada"
		#define STR0103 "Item no localizado"
		#define STR0104 "¡Esta ocurrencia exige reversion de los items leidos de este producto!"
		#define STR0105 "No existen items para revertir"
		#define STR0106 "Reversion"
		#define STR0107 "Por Producto"
		#define STR0108 "Por Direccion"
		#define STR0109 "Reversion selecione:"
		#define STR0110 "Reversion de la lectura"
		#define STR0111 "Lea el Almacen"
		#define STR0112 "Reversion Cantidad "
		#define STR0113 "Rev.Ctd. "
		#define STR0114 "Etiqueta de volumen invalida"
		#define STR0115 "Volume pertenece a otra orden de separacion"
		#define STR0116 "Direccion diferente"
		#define STR0117 "Producto no separado"
		#define STR0118 "Item no encontrado"
		#define STR0119 "Volumen o etiqueta invalida"
		#define STR0120 "Cantidad informada mayor que la separada"
		#define STR0121 "¿Confirma la reversion?"
		#define STR0122 "Operador: "
		#define STR0123 " Orden de Separacion: "
		#define STR0124 "Confirma la solcitud de los items?"
		#define STR0125 "¿Confirma la reversion de la solicitud de los items?"
		#define STR0126 "Procesando"
#else
	#ifdef ENGLISH
		#define STR0001 "Separacao"
		#define STR0002 "Selecione:"
		#define STR0003 "Ordem de Separacao"
		#define STR0004 "Pedido de Venda"
		#define STR0005 "Nota Fiscal"
		#define STR0006 "Ordem Producao"
		#define STR0007 "Expedicao"
		#define STR0008 "Expedicao Selecione"
		#define STR0009 "Operador nao cadastrado"
		#define STR0010 "Aviso"
		#define STR0011 "O conteudo informado no parametro MV_IACD01 deve existir na tabela CB5."
		#define STR0012 "Processo de separacao finalizado"
		#define STR0013 "Deseja estornar a separacao ?"
		#define STR0014 "Atencao"
		#define STR0015 "Informacoes"
		#define STR0016 "Estorna"
		#define STR0017 "Ultima Tela"
		#define STR0018 "Volume"
		#define STR0019 "Confirma a saida?"
		#define STR0020 "Pula"
		#define STR0021 "Div.Etiqueta"
		#define STR0022 "Div.Pallet"
		#define STR0023 "Ainda existem itens nao separados. Deseja separalos agora?"
		#define STR0024 "Va para o armazem"
		#define STR0025 "Enter para continuar"
		#define STR0026 "Va para o armazem "
		#define STR0027 "Va p/ o armazem "
		#define STR0028 "Va para o endereco"
		#define STR0029 "Falha na gravacao movimentacao TM "
		#define STR0030 "Leia o endereco"
		#define STR0031 "Inconsistencia de Base, produto "
		#define STR0032 " nao encontrado"
		#define STR0033 "item "
		#define STR0034 "itens "
		#define STR0035 "volume "
		#define STR0036 "volumes "
		#define STR0037 "Separe "
		#define STR0038 "Lote: "
		#define STR0039 "Produto"
		#define STR0040 "Descricao"
		#define STR0041 "Qtde"
		#define STR0042 "Lote"
		#define STR0043 "Sub-Lote"
		#define STR0044 "Num. Serie"
		#define STR0045 "Separe"
		#define STR0046 "Leia a etiqueta"
		#define STR0047 "Qtde "
		#define STR0048 "Leia o produto"
		#define STR0049 "Leia a caixa"
		#define STR0050 "Leia a etiq. avulsa"
		#define STR0051 "Item separado nao localizado!"
		#define STR0052 "Quantidade"
		#define STR0053 "Armazem"
		#define STR0054 "Endereco"
		#define STR0055 "Sub-Volume"
		#define STR0056 "Num.Serie"
		#define STR0057 "Id Etiqueta"
		#define STR0058 "Embalagem"
		#define STR0059 "Leia o volume:"
		#define STR0060 "Tecle ENTER para"
		#define STR0061 "novo volume.    "
		#define STR0062 "Leia o volume ou ENTER p/ novo volume"
		#define STR0063 "Leia o volume"
		#define STR0064 "Digite o codigo do"
		#define STR0065 "tipo de embalagem"
		#define STR0066 "Imprimindo etiqueta de volume "
		#define STR0067 "Etiqueta invalida"
		#define STR0068 "Codigo de volume nao cadastrado"
		#define STR0069 "Volume pertence ao pedido "
		#define STR0070 "Volume pertence a nota "
		#define STR0071 "Embalagem nao cadastrada"
		#define STR0072 "Ordem de separacao nao encontrada."
		#define STR0073 "Ordem de Pre-Separacao "
		#define STR0074 "Codigo Invalido"
		#define STR0075 "Ordem de separacao em processo de embalagem"
		#define STR0076 "Ordem de separacao com embalagem finalizada"
		#define STR0077 "Ordem de separacao possui Nota gerada"
		#define STR0078 "Ordem de separacao possui etiquetas oficiais de volumes"
		#define STR0079 "Ordem de separacao em processo de embarque"
		#define STR0080 "Ordem de separacao ja Embarcada"
		#define STR0081 "Ordem Separacao iniciada pelo operador "
		#define STR0082 ". Deseja continuar ?"
		#define STR0083 "Ordem Separacao ja esta em andamento...!"
		#define STR0084 "Endereco invalido"
		#define STR0085 "Endereco Bloqueado."
		#define STR0086 "Etiqueta invalida, Produto pertence a um Pallet"
		#define STR0087 "Endereco associado a esta etiqueta esta diferente"
		#define STR0088 "Etiqueta ja lida"
		#define STR0089 "Produto diferente"
		#define STR0090 "Quantidade maior que necessario"
		#define STR0091 "Lote invalido"
		#define STR0092 "Lote nao existe"
		#define STR0093 "Saldo em estoque insuficiente"
		#define STR0094 "Pallet excede a quantidade a separar"
		#define STR0095 "Etiqueta de produto diferente"
		#define STR0096 "Quantidade invalida"
		#define STR0097 "Quantidade maior que solicitado"
		#define STR0098 "Informe o codigo"
		#define STR0099 "da divergencia:"
		#define STR0100 "Informe o codigo da divergencia:"
		#define STR0101 "Divergencia:"
		#define STR0102 "Ocorrencia nao cadastrada"
		#define STR0103 "Item nao localizado"
		#define STR0104 "Esta ocorrencia exige o estorno dos itens lidos deste produto!"
		#define STR0105 "Nao existe itens  a serem Estornados"
		#define STR0106 "Estorno"
		#define STR0107 "Por Produto"
		#define STR0108 "Por Endereco"
		#define STR0109 "Estorno selecione:"
		#define STR0110 "Estorno da leitura"
		#define STR0111 "Leia o Armazem"
		#define STR0112 "Estorno Qtde "
		#define STR0113 "Est.Qtde "
		#define STR0114 "Etiqueta de volume invalida"
		#define STR0115 "Volume pertence a outra ordem de separacao"
		#define STR0116 "Endereco diferente"
		#define STR0117 "Produto nao separado"
		#define STR0118 "Item nao encontrado"
		#define STR0119 "Volume ou etiqueta invalida"
		#define STR0120 "Quantidade informada maior do que separada"
		#define STR0121 "Confirma o estorno?"
		#define STR0122 "Operador: "
		#define STR0123 " Ordem de Separacao: "
		#define STR0124 "Confirma a requisicao dos itens?"
		#define STR0125 "Confirma o estorno da requisicao dos itens?"
		#define STR0126 "Processando"
	#else
		#define STR0001 "Separacao"
		#define STR0002 "Selecione:"
		#define STR0003 "Ordem de Separacao"
		#define STR0004 "Pedido de Venda"
		#define STR0005 "Nota Fiscal"
		#define STR0006 "Ordem Producao"
		#define STR0007 "Expedicao"
		#define STR0008 "Expedicao Selecione"
		#define STR0009 "Operador nao cadastrado"
		#define STR0010 "Aviso"
		#define STR0011 "O conteudo informado no parametro MV_IACD01 deve existir na tabela CB5."
		#define STR0012 "Processo de separacao finalizado"
		#define STR0013 "Deseja estornar a separacao ?"
		#define STR0014 "Atencao"
		#define STR0015 "Informacoes"
		#define STR0016 "Estorna"
		#define STR0017 "Ultima Tela"
		#define STR0018 "Volume"
		#define STR0019 "Confirma a saida?"
		#define STR0020 "Pula"
		#define STR0021 "Div.Etiqueta"
		#define STR0022 "Div.Pallet"
		#define STR0023 "Ainda existem itens nao separados. Deseja separalos agora?"
		#define STR0024 "Va para o armazem"
		#define STR0025 "Enter para continuar"
		#define STR0026 "Va para o armazem "
		#define STR0027 "Va p/ o armazem "
		#define STR0028 "Va para o endereco"
		#define STR0029 "Falha na gravacao movimentacao TM "
		#define STR0030 "Leia o endereco"
		#define STR0031 "Inconsistencia de Base, produto "
		#define STR0032 " nao encontrado"
		#define STR0033 "item "
		#define STR0034 "itens "
		#define STR0035 "volume "
		#define STR0036 "volumes "
		#define STR0037 "Separe "
		#define STR0038 "Lote: "
		#define STR0039 "Produto"
		#define STR0040 "Descricao"
		#define STR0041 "Qtde"
		#define STR0042 "Lote"
		#define STR0043 "Sub-Lote"
		#define STR0044 "Num. Serie"
		#define STR0045 "Separe"
		#define STR0046 "Leia a etiqueta"
		#define STR0047 "Qtde "
		#define STR0048 "Leia o produto"
		#define STR0049 "Leia a caixa"
		#define STR0050 "Leia a etiq. avulsa"
		#define STR0051 "Item separado nao localizado!"
		#define STR0052 "Quantidade"
		#define STR0053 "Armazem"
		#define STR0054 "Endereco"
		#define STR0055 "Sub-Volume"
		#define STR0056 "Num.Serie"
		#define STR0057 "Id Etiqueta"
		#define STR0058 "Embalagem"
		#define STR0059 "Leia o volume:"
		#define STR0060 "Tecle ENTER para"
		#define STR0061 "novo volume.    "
		#define STR0062 "Leia o volume ou ENTER p/ novo volume"
		#define STR0063 "Leia o volume"
		#define STR0064 "Digite o codigo do"
		#define STR0065 "tipo de embalagem"
		#define STR0066 "Imprimindo etiqueta de volume "
		#define STR0067 "Etiqueta invalida"
		#define STR0068 "Codigo de volume nao cadastrado"
		#define STR0069 "Volume pertence ao pedido "
		#define STR0070 "Volume pertence a nota "
		#define STR0071 "Embalagem nao cadastrada"
		#define STR0072 "Ordem de separacao nao encontrada."
		#define STR0073 "Ordem de Pre-Separacao "
		#define STR0074 "Codigo Invalido"
		#define STR0075 "Ordem de separacao em processo de embalagem"
		#define STR0076 "Ordem de separacao com embalagem finalizada"
		#define STR0077 "Ordem de separacao possui Nota gerada"
		#define STR0078 "Ordem de separacao possui etiquetas oficiais de volumes"
		#define STR0079 "Ordem de separacao em processo de embarque"
		#define STR0080 "Ordem de separacao ja Embarcada"
		#define STR0081 "Ordem Separacao iniciada pelo operador "
		#define STR0082 ". Deseja continuar ?"
		#define STR0083 "Ordem Separacao ja esta em andamento...!"
		#define STR0084 "Endereco invalido"
		#define STR0085 "Endereco Bloqueado."
		#define STR0086 "Etiqueta invalida, Produto pertence a um Pallet"
		#define STR0087 "Endereco associado a esta etiqueta esta diferente"
		#define STR0088 "Etiqueta ja lida"
		#define STR0089 "Produto diferente"
		#define STR0090 "Quantidade maior que necessario"
		#define STR0091 "Lote invalido"
		#define STR0092 "Lote nao existe"
		#define STR0093 "Saldo em estoque insuficiente"
		#define STR0094 "Pallet excede a quantidade a separar"
		#define STR0095 "Etiqueta de produto diferente"
		#define STR0096 "Quantidade invalida"
		#define STR0097 "Quantidade maior que solicitado"
		#define STR0098 "Informe o codigo"
		#define STR0099 "da divergencia:"
		#define STR0100 "Informe o codigo da divergencia:"
		#define STR0101 "Divergencia:"
		#define STR0102 "Ocorrencia nao cadastrada"
		#define STR0103 "Item nao localizado"
		#define STR0104 "Esta ocorrencia exige o estorno dos itens lidos deste produto!"
		#define STR0105 "Nao existe itens  a serem Estornados"
		#define STR0106 "Estorno"
		#define STR0107 "Por Produto"
		#define STR0108 "Por Endereco"
		#define STR0109 "Estorno selecione:"
		#define STR0110 "Estorno da leitura"
		#define STR0111 "Leia o Armazem"
		#define STR0112 "Estorno Qtde "
		#define STR0113 "Est.Qtde "
		#define STR0114 "Etiqueta de volume invalida"
		#define STR0115 "Volume pertence a outra ordem de separacao"
		#define STR0116 "Endereco diferente"
		#define STR0117 "Produto nao separado"
		#define STR0118 "Item nao encontrado"
		#define STR0119 "Volume ou etiqueta invalida"
		#define STR0120 "Quantidade informada maior do que separada"
		#define STR0121 "Confirma o estorno?"
		#define STR0122 "Operador: "
		#define STR0123 " Ordem de Separacao: "
		#define STR0124 "Confirma a requisicao dos itens?"
		#define STR0125 "Confirma o estorno da requisicao dos itens?"
		#define STR0126 "Processando"
	#endif
#endif
